title: Botsafe Project
description: Learn from previous security-related Meower bot mistakes before you make yours.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
